### ISSUE TITLE
Bug with onSubmitEditing

### ISSUE THREAD

**Issue by hnnweb** [amirfl/react-native-num-textinput#1]
With the following code:
`<NumericalTextInput
            style={styles.textinput}
            ref='UsernameInput'
            returnKeyType = {"next"}
            onChangeText={(text) => this.setState({username: text})}
            value={this.state.username}
            placeholder={"Username"}
            autoFocus={true}
            onSubmitEditing={(event) => {
                this.refs.PasswordInput.focus();
            }}
            />
          <NumericalTextInput
            ref='PasswordInput'
            style={styles.textinput}
            returnKeyType = {"send"}
            onChangeText={(text) => this.setState({password: text})}
            value={this.state.password}
            secureTextEntry={true}
            placeholder={"Password"}
            onSubmitEditing={(event) => {
                this.login()
            }}
          />`

i get the following error in the attached image:

![screen shot 2016-08-10 at 16 20 07](https://cloud.githubusercontent.com/assets/3874960/17557125/54b73fca-5f16-11e6-9bcb-5cceff1f1b7e.png)

Works perfectly with TextInput Component.

Code on line 60 is:

`this.refs.PasswordInput.focus();`

**Comment by amirfl** [comment]
I believe the problem might be with scoping of 'this'.
Try using .bind(this).

Something like:
`onSubmitEditing={(event) => { this.refs.PasswordInput.focus().bind(this); }}
`

**Comment by hnnweb** [comment]
Still the same error

**Comment by amirfl** [comment]
I just made a new commit that should solve this problem
